spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@codingz2m.ytv7d9l.mongodb.net/?retryWrites=true&w=majority
      database: productsdb

#spring:
#  data:
#    mongodb:
#      database: productsdb
#      host: localhost
#      port: 27017
            
server:
  port: 8081
  
  
   